### ISSUE TITLE
[CKEditor] CKEditor bug using lists

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8166] opened 2021-06-09 14:32 UTC
**Describe the bug**
https://www.kunena.org/forum/k-5-2-support/161828-ckeditor-bug-using-lists

**To Reproduce**
Open the editor and choose the Source mode
Enter a code like this:
```
[b]header[/b]
[list]
[*]line 1
[*]line 2
[*]line 3
[/list]
```
Now switch several times between Source and Normal mode and you see the problem

**Actual result**
It adds new code tags every time and messes everything up. The same occur if you want to edit a message with a list.

**Screenshots**
![Bildschirmfoto von 2021-06-09 16-06-02](https://user-images.githubusercontent.com/888847/121371146-9da5aa00-c93d-11eb-9154-e4effab14438.png)

**Additional context**
The same does not happens on the Test-CKEditor, maybe it's a conflict with one of our plugins.
https://ckeditor.com/docs/ckeditor4/latest/examples/bbcode.html

**Comment by 810** [comment] 2021-06-09 14:43
I can't reproduce this issue. (tested on K6.0)

**Comment by Ruud68** [comment] 2021-06-27 07:28
just ran into this issue with [url]...[/url]
so now it is also impossible to edit a post with an url in it

@810 the issue is on 5, not 6. maybe there is some hint as to why it is working correct on 6 and not on 5?

**Comment by baticag** [comment] 2021-06-27 15:53
This editor or implemention of it is shit... Errors with every bbcode tag... it's duplicating them, pushing them to the end. Please fix this issues or give us the option back to change to classic editor.

**Comment by Ruud68** [comment] 2021-06-28 08:25
when reverting this PR  #8115 (so basically reverting ckeditor.js back to version 4.16.0) everything is working again.
I cannot reproduce this issue on the ckeditor website :(
Is kunena using a custom build of ckeditor 4?

**Comment by Ruud68** [comment] 2021-06-28 08:28
ping @xillibit for relation to #8115

**Comment by Ruud68** [comment] 2021-06-28 08:41
So for any body for whom this is a blocking issue (me :S).
make a backup of ./media/kunena/core/js/ckeditor.js
then replace the contents of ckeditor.js with this one: https://raw.githubusercontent.com/Kunena/Kunena-Forum/a5fe11dfed4795e70f6b946d125a9090a62d6e6a/src/media/kunena/core/js/ckeditor.js

This will revert the editor version back to 4.16.0 that doesn't have this issue.
Note this is a workaround and may re-introduce other issues solved in (custom) 4.16.1

**Comment by rich20** [comment] 2021-06-28 14:32
>I can't reproduce this issue. (tested on K6.0)

It works, because K6.0 contain still the ckeditor.js 4.16.0
I've tested it with
Crypsis
Crypsisb3
Crypsisb4
Aurelia
In fact, this bug occurs on all versions, also with Kunena 6.0 with the ckeditor.js v4.16.1

This change in line 1275 causes the conflict
from
`				for(var b = [], c = [], g = d; g.type && g.name != a;) g._.isBlockLike || c.unshift(g), b.push(g), g = g.parent;
				if(g.type) {
					for(e = 0; e < b.length; e++) a = b[e], k(a, a.parent);
					d = g;
					k(g, g.parent);
					g == d && (d = d.parent);
					h = h.concat(c)`
to
`				var b = [],
					c = [],
					g = d;
				if(1 == g) {
					for(; g.type && g.name != a;) g._.isBlockLike || c.unshift(g), b.push(g), g = g.parent;
					if(g.type) {
						for(e = 0; e < b.length; e++) a = b[e], k(a, a.parent);
						d = g;
						k(g, g.parent);
						g == d && (d = d.parent);
						h = h.concat(c)
					}`

**Comment by Ruud68** [comment] 2021-06-28 15:15
@rich20 does Kunena use a customized ckeditor.js or is it the out-of-the-box one? I have tried using the ckeditor.js from the ckeditor download (standard), but that didn't load in Kunena making me think you have a customized version?

The code in ckeditor.js is minified so impossible to debug / troubleshoot :( (at least for me :))

**Comment by rich20** [comment] 2021-06-28 15:35
The ckeditor.js is original, only the ckeditor_config.js is customized.
>The code in ckeditor.js is minified so impossible to debug / troubleshoot :( (at least for me :))

I decompress the files first before compare. And this code block is the only one change between both files, so you can use the ckeditor.js 4.16.0 furthermore.

**Comment by Ruud68** [comment] 2021-06-29 08:16
I have just used the online ckeditor builder and created a new ckeditor.zip file. latest 4.16.1 version
I have extracted the contents into media/kunena/core/js

The issue is now solved ?!

So I think this can be fixed with building a new ckeditor (with the settings Kunena uses) and copying that over the current files.
I can do a PR for that, but I do not know what settings kunena team uses when building the editor (languages, skin, bbcode plugin / other plugins, basic / standard / full, etc.

**Comment by xillibit** [comment] 2021-06-29 15:28
It should be more easier to use the build.js, when i generate from online builder i remove all the useless parts

**Comment by Ruud68** [comment] 2021-06-29 15:46
> It should be more easier to use the build.js, when i generate from online builder i remove all the useless parts

tried that but wasn't able to get the BBcode working (it looked like a mixture of bbcode and html), feel like I'm already learning to much new stuff here :) This should just work as the editor is key to what users do with Kunena: if the editor doesn't work, Kunena doesn't work.

If you could give it a try: I can test :)

**Closed as completed** 2021-06-29 18:37 UTC
Labels: bug
