### ISSUE TITLE
Description corrupted when Email = 32 characters

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4332] opened 2016-08-16 14:56 UTC
#### Steps to reproduce the issue
1. Apply this fix: https://github.com/Kunena/Kunena-Forum/commit/f9190214195983f65f44558ffdb03be989ef0424
2. Create a new topic and insert a 32 characters email in the content
#### Expected result

![good](https://cloud.githubusercontent.com/assets/12942731/17703450/c4d7b694-639f-11e6-8c30-0683920e39b6.png)
#### Actual result

![corrupted](https://cloud.githubusercontent.com/assets/12942731/17703456/c7f61d20-639f-11e6-84e0-afcb56a9360c.png)
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0
Php version: 7.0.9
Database version: 5.6.31

**Comment by 810** [comment] 2016-08-16 15:52
i can't reproduce this issue

**Comment by sshcli** [comment] 2016-08-16 19:01
That's because this function is not working as expected in K.5.0.1-dev
In the description window you should see the content of the message (Not title)

**Comment by 810** [comment] 2016-08-16 19:15
what is you message text then

**Comment by 810** [comment] 2016-08-16 19:46
same for tweet

**Comment by 810** [comment] 2016-09-06 15:17
is now fixed

**Closed as completed** 2016-09-06 18:19 UTC
Labels: bug
