### ISSUE TITLE
Change vote second time

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#5780] opened 2018-03-07 18:10 UTC
#### Steps to reproduce the issue

When you change the vote for the second time you will get a error:

#### Expected result

correct saved

#### Actual result

Kunena Internal Error: Please enable Kunena Debug Mode and report problem in the www.kunena.org forum.

Adding vote to user failed!

The new vote is added but also the old vote still there. First time change is correct, but more, there is a error

#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by rich20** [comment] 2018-03-21 17:58
Do you mean with "vote" the poll options? I can't reproduce this problem. I've changed it many times, but no error.

**Comment by 810** [comment] 2018-03-21 18:17
set single vote to "no" and 

Time Between Consecutive Votes to 00:00:10

then vote for the first option. 
click on change vote after 10 seconds, select option 2. then you have the error, and both options has 1 vote.

**Comment by rich20** [comment] 2018-03-21 18:24
ah.. I confirm the Kunena Internal Error

**Comment by rich20** [comment] 2018-04-29 14:50
The error still exist. Change the vote again and you will see it. <strike>We have two errors:</strike>

- [x] Change vote again
- [ ] Time Between Consecutive Votes - this time will ignored, you can always to change the vote

**Comment by 810** [comment] 2018-04-30 22:45
Should be fixed now, please test

**Comment by rich20** [comment] 2018-05-01 02:02
Change vote seems fixed now. You see the change button only after the choosen time period. Previously you have no change button. But we have the next bug now. 
If you create a new poll, you get no Vote button. You can to change already exists polls, but in a new poll no voting.

**Closed as completed** 2018-05-01 02:47 UTC
Labels: bug, top, Release Blocker
