### ISSUE TITLE
Template Aurelia 6.0.3 Login and profiles problem

### ISSUE THREAD

**Issue by fotofreunde** [Kunena/Kunena-Forum#9306] opened 2022-10-13 17:12 UTC
Hi!
I can't log in on my smartphone.
1. Go to [https://fotofreunde-telegram.eu/forum]
2. 
![Screenshot_148](https://user-images.githubusercontent.com/115731598/195661072-af34eef4-ef71-485c-afe2-06e8a79ebb94.jpg)
3. Is everything on right side.
4. Recent posts are not displayed.
5. 
![Screenshot_136](https://user-images.githubusercontent.com/115731598/195661799-c4ca5d5a-4e01-47ef-808a-5879c9535b9c.jpg)

Joomla version: 4.2.3
Kunena version: 6.0.3
Php version: 8.1
Database version:  MariaDB 10.3.36	

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Browser firefox
 - Version 105.0.3

**Smartphone (please complete the following information):**
 - Device: OnePlus Nord 2
 - Browser firefox

**Comment by rich20** [comment] 2022-10-13 18:51
Login problem confirmed. The console shows:

`aktuell:1 An invalid form control with name='username' is not focusable. <input class=​"form-control" id=​"kmobile-username" name=​"username" tabindex=​"1" autocomplete=​"username" placeholder=​"Username" type=​"email">​      218-rich:1`

But I cannot confirm the display problem:
.
![Bildschirmfoto vom 2022-10-13 20-05-54](https://user-images.githubusercontent.com/888847/195681274-64d9e5c8-21d1-46ea-96ab-f15622f03730.png)

**Comment by fotofreunde** [comment] 2022-10-13 19:04
> Login problem confirmed. The console shows:
> 
> `aktuell:1 An invalid form control with name='username' is not focusable. <input class=​"form-control" id=​"kmobile-username" name=​"username" tabindex=​"1" autocomplete=​"username" placeholder=​"Username" type=​"email">​ 218-rich:1`
> 
> But I cannot confirm the display problem: . ![Bildschirmfoto vom 2022-10-13 20-05-54](https://user-images.githubusercontent.com/888847/195681274-64d9e5c8-21d1-46ea-96ab-f15622f03730.png)

Is since update from 6.03
In category on smartphone

**Comment by Ruud68** [comment] 2022-10-16 14:25
> Login problem confirmed. The console shows:
> 
> `aktuell:1 An invalid form control with name='username' is not focusable. <input class=​"form-control" id=​"kmobile-username" name=​"username" tabindex=​"1" autocomplete=​"username" placeholder=​"Username" type=​"email">​ 218-rich:1`
> 
> But I cannot confirm the display problem: . ![Bildschirmfoto vom 2022-10-13 20-05-54](https://user-images.githubusercontent.com/888847/195681274-64d9e5c8-21d1-46ea-96ab-f15622f03730.png)

fixed with #9308

**Comment by rich20** [comment] 2022-10-17 15:40
> fixed with https://github.com/Kunena/Kunena-Forum/pull/9308

- [x] This fix was successful, so I'm closing here.

**Closed as completed by rich20** 2022-10-17 15:40 UTC
Labels: bug

**Comment by fotofreunde** [comment] 2022-10-20 09:33
> > fixed with #9308
> 
>     * [x]  This fix was successful, so I'm closing here.
Hi!
I'm sorry to get back to you.
Having trouble logging in again.
Registration is again on the left side.
Google Bot shows that it sees 2 login buttons.
I don't know but my posts are not indexed on Google now.
![Screenshot_167](https://user-images.githubusercontent.com/115731598/196912400-e8b1f76b-c5e9-421c-b45b-1801f8270702.jpg)
![Screenshot_165](https://user-images.githubusercontent.com/115731598/196912404-c2e7af35-13f8-4c7d-b739-6f5c08167959.jpg)
![Screenshot_166](https://user-images.githubusercontent.com/115731598/196912407-a9054b26-1a5b-4b76-ae01-9484112aaff3.jpg)

**Comment by Ruud68** [comment] 2022-10-20 12:19
Hi as for google and the google bot: in the webmaster tools they fetch your page but limit the number of css files they fetch with it. What I read is that they have some algorithm 'guessing' what css files are important to load.
As you can see the bot shows your page with double login form: this is correct and due to not loading the css that is responsible for hiding one of the login forms (as that is done by css depending on your device width)

You can see that in the google tab 'Weitere informationen' there is listed what css /js files where not loaded.

as for you not able to login / the menu not showing on your site: can you provide me with an url to your form so i can have a look?

**Comment by fotofreunde** [comment] 2022-10-20 13:11
> Hi as for google and the google bot: in the webmaster tools they fetch your page but limit the number of css files they fetch with it. What I read is that they have some algorithm 'guessing' what css files are important to load. As you can see the bot shows your page with double login form: this is correct and due to not loading the css that is responsible for hiding one of the login forms (as that is done by css depending on your device width)
> 
> You can see that in the google tab 'Weitere informationen' there is listed what css /js files where not loaded.
> 
> as for you not able to login / the menu not showing on your site: can you provide me with an url to your form so i can have a look?

my page is here https://fotofreunde-telegram.eu/forum
 error is only on desktop pc.login is on left side.

**Comment by Ruud68** [comment] 2022-10-20 14:23
Hi,
your template is using bootstrap version 5.0.2. and not the joomla / kunena provided 5.1.3
This bootstrap css that is responsible for toggling the offcanvas menu / button is different in bootstrap 5.1.3 (shipped with Joomla 4.2) and higher. I use Bootstrap 5.2 template myself: here it is also working correct.
You can test that by (while on the forum page) switching the template to casseopia and refresh the forum page: it should then display okay on different screen sizes.

is there a newer / updated version for your (gantry) template?
did you configure Kunena to NOT oad Bootstrap (in aurelia template)?

**Comment by fotofreunde** [comment] 2022-10-20 15:07
> Hi, your template is using bootstrap version 5.0.2. and not the joomla / kunena provided 5.1.3 This bootstrap css that is responsible for toggling the offcanvas menu / button is different in bootstrap 5.1.3 (shipped with Joomla 4.2) and higher. I use Bootstrap 5.2 template myself: here it is also working correct. You can test that by (while on the forum page) switching the template to casseopia and refresh the forum page: it should then display okay on different screen sizes.
> 
> is there a newer / updated version for your (gantry) template? did you configure Kunena to NOT oad Bootstrap (in aurelia template)?

Please check. I turned off Bootstrap. It does not work

**Comment by Ruud68** [comment] 2022-10-20 15:23
Issue is with your template loading old bootstrap that doesn't have support for what we are trying to do.
So either update gantry with version that has latest bootstrap version, or try to enable bootstrap css in aurelia template and see if that then loads the joomla Bootstrap (which is good version)

**Comment by fotofreunde** [comment] 2022-10-20 16:07
> Issue is with your template loading old bootstrap that doesn't have support for what we are trying to do. So either update gantry with version that has latest bootstrap version, or try to enable bootstrap css in aurelia template and see if that then loads the joomla Bootstrap (which is good version)
Have now installed Ganzry 5.5.15. Unfortunately I didn't come to check if everything works. M traveling

**Comment by Ruud68** [comment] 2022-10-21 06:47
Hi, just checked: still the same. It also doesn't load bootstrap via Kunena. Did you configure Kunena template Aurelia to load bootstrap? If so it should load Joomla provided bootstrap which is not having this issue.
![image](https://user-images.githubusercontent.com/2733197/197130832-e9553394-db3a-49d0-befb-9d94b2966539.png)

**Comment by fotofreunde** [comment] 2022-10-21 07:25
> Hi, just checked: still the same. It also doesn't load bootstrap via Kunena. Did you configure Kunena template Aurelia to load bootstrap? If so it should load Joomla provided bootstrap which is not having this issue. ![image](https://user-images.githubusercontent.com/2733197/197130832-e9553394-db3a-49d0-befb-9d94b2966539.png)

Good morning!
Cassiopeia works.
Have Gantry Version: 5.5.15 / Released: September 5, 2022
Load Bootstrap css: Yes
Please see screenshot.
![Screenshot_168](https://user-images.githubusercontent.com/115731598/197137530-64398d5d-4ec3-42ab-a7bb-f56a64556955.jpg)
![Screenshot_169](https://user-images.githubusercontent.com/115731598/197137535-6cb04a06-a677-4193-8cc9-51657ca64aaa.jpg)
![Screenshot_170](https://user-images.githubusercontent.com/115731598/197137538-8bbc1062-4702-4791-be5c-ab4f36f50d59.jpg)

**Comment by fotofreunde** [comment] 2022-10-21 07:26
> > Hi, just checked: still the same. It also doesn't load bootstrap via Kunena. Did you configure Kunena template Aurelia to load bootstrap? If so it should load Joomla provided bootstrap which is not having this issue. ![image](https://user-images.githubusercontent.com/2733197/197130832-e9553394-db3a-49d0-befb-9d94b2966539.png)
> 
> Good morning! Cassiopeia works. Have Gantry Version: 5.5.15 / Released: September 5, 2022 Load Bootstrap css: Yes Please see screenshot. ![Screenshot_168](https://user-images.githubusercontent.com/115731598/197137530-64398d5d-4ec3-42ab-a7bb-f56a64556955.jpg) ![Screenshot_169](https://user-images.githubusercontent.com/115731598/197137535-6cb04a06-a677-4193-8cc9-51657ca64aaa.jpg) ![Screenshot_170](https://user-images.githubusercontent.com/115731598/197137538-8bbc1062-4702-4791-be5c-ab4f36f50d59.jpg)

![Screenshot_171](https://user-images.githubusercontent.com/115731598/197137860-a084e07c-b572-4153-b054-76570d2268d3.jpg)

**Comment by Ruud68** [comment] 2022-10-21 07:34
@xillibit can you advice. This turns out to be a template issue (Gantry used is on outdated BS version that has a bug / broken implementation for offCanvas.
What is strange is that although aurelia is set to load Bootstrap css it actually doesn't load?

So should we while developing build upon joomla provided BS or take into account lower BS5 versions that come with some templates?

EDIT: just see that with option Load Bootstrap CSS, all BS javascript functions are loaded, but not the Bootstrap css itsself?

**Comment by Ruud68** [comment] 2022-10-21 08:01
@fotofreunde 
can you try this code change:
in file ./components/com_kunena/template/aurelia/template.php change (line 109):
```
		if ($bootstrap)
		{
			HTMLHelper::_('bootstrap.dropdown');
			HTMLHelper::_('bootstrap.tooltip');
			HTMLHelper::_('bootstrap.renderModal');
			HTMLHelper::_('bootstrap.collapse');
			HTMLHelper::_('bootstrap.offcanvas');
			HTMLHelper::_('bootstrap.alert');
		}
```
to 
```
		if ($bootstrap)
		{
            		HTMLHelper::_('bootstrap.loadCss');
			HTMLHelper::_('bootstrap.dropdown');
			HTMLHelper::_('bootstrap.tooltip');
			HTMLHelper::_('bootstrap.renderModal');
			HTMLHelper::_('bootstrap.collapse');
			HTMLHelper::_('bootstrap.offcanvas');
			HTMLHelper::_('bootstrap.alert');
		}
```

**Comment by fotofreunde** [comment] 2022-10-21 08:44
> @fotofreunde can you try this code change: in file ./components/com_kunena/template/aurelia/template.php change (line 109):
> 
> ```
> 		if ($bootstrap)
> 		{
> 			HTMLHelper::_('bootstrap.dropdown');
> 			HTMLHelper::_('bootstrap.tooltip');
> 			HTMLHelper::_('bootstrap.renderModal');
> 			HTMLHelper::_('bootstrap.collapse');
> 			HTMLHelper::_('bootstrap.offcanvas');
> 			HTMLHelper::_('bootstrap.alert');
> 		}
> ```
> 
> to
> 
> ```
> 		if ($bootstrap)
> 		{
>             		HTMLHelper::_('bootstrap.loadCss');
> 			HTMLHelper::_('bootstrap.dropdown');
> 			HTMLHelper::_('bootstrap.tooltip');
> 			HTMLHelper::_('bootstrap.renderModal');
> 			HTMLHelper::_('bootstrap.collapse');
> 			HTMLHelper::_('bootstrap.offcanvas');
> 			HTMLHelper::_('bootstrap.alert');
> 		}
> ```

Perfect
![Screenshot_172](https://user-images.githubusercontent.com/115731598/197153405-c4f9c04d-d3b3-4e66-99f5-0a02232a1e6c.jpg)

Now everything works

**Comment by Ruud68** [comment] 2022-10-21 08:53
@fotofreunde good to hear! @xillibit did a PR to fix this i aurelia
