### ISSUE TITLE
It's not possible to unpublish categories

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8162] opened 2021-06-08 16:56 UTC
**Describe the bug**
You get this error if you mark the checkbox and click on Unpublish:

Kunena\Forum\Libraries\Forum\Category\KunenaCategory::isCheckedOut(): Argument #1 ($with) must be of type string, null given, called in /www/.../administrator/components/com_kunena/src/Controller/CategoriesController.php on line 134

**System information (please complete the following information)**
- Joomla version: 4.0.0-rc2-dev
- Kunena version: 6.0.0-BETA1
- Kunena template name and version: Aurelia
- Php version: 8.0.1 and 7.4.14
- Database version: 10.5.10-MariaDB-1:10.5.10

**Comment by 810** [comment] 2021-06-09 14:15
Should now be fixed with the other fix. please try again.

**Comment by xillibit** [comment] 2021-06-19 17:45
Still not able to reproduce it

**Comment by rich20** [comment] 2021-06-20 15:43
>Should now be fixed with the other fix. please try again.

I only see the two last fixes from you. https://github.com/Kunena/Kunena-Forum/issues/8186 and https://github.com/Kunena/Kunena-Forum/issues/8184
Only the row of error has changed.

0 Argument 1 passed to Kunena\Forum\Libraries\Forum\Category\KunenaCategory::isCheckedOut() must be of the type string, null given, called in /.../administrator/components/com_kunena/src/Controller/CategoriesController.php on line 130


**Call stack**
--
# | Function | Location
1 | () | JROOT/libraries/kunena/src/Forum/Category/KunenaCategory.php:1743
2 | Kunena\Forum\Libraries\Forum\Category\KunenaCategory-&gt;isCheckedOut() | JROOT/administrator/components/com_kunena/src/Controller/CategoriesController.php:130
3 | Kunena\Forum\Administrator\Controller\CategoriesController-&gt;setVariable() | JROOT/administrator/components/com_kunena/src/Controller/CategoriesController.php:339
4 | Kunena\Forum\Administrator\Controller\CategoriesController-&gt;unpublish() | JROOT/libraries/src/MVC/Controller/BaseController.php:730
5 | Joomla\CMS\MVC\Controller\BaseController-&gt;execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:146
6 | Joomla\CMS\Dispatcher\ComponentDispatcher-&gt;dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:389
7 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:143
8 | Joomla\CMS\Application\AdministratorApplication-&gt;dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:186
9 | Joomla\CMS\Application\AdministratorApplication-&gt;doExecute() | JROOT/libraries/src/Application/CMSApplication.php:278
10 | Joomla\CMS\Application\CMSApplication-&gt;execute() | JROOT/administrator/includes/app.php:63
11 | require_once() | JROOT/administrator/index.php:32

**Closed as completed** 2021-06-20 17:17 UTC
Labels: bug, Backend
