### ISSUE TITLE
Kunena<->Joomla authentication broken on Joomla 4.3.0

### ISSUE THREAD

**Issue by c-schmitz** [Kunena/Kunena-Forum#9516] opened 2023-04-26 12:05 UTC
**Describe the bug**
When installing Kunena on Joomla 4.3.0 and use the direct Kunena<>Joomla authentication plugin you will get an error 
(see pic below)

**To Reproduce**
1. Click the menu link to log into Kunena. Enter username password in the menu dropdown and click the Login buttin.

**Expected behavior**
Log in to Joomla.
**Actual result**
Error is shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/1364282/234568625-58313b87-e6ce-4cc8-98f6-2916211a7d2d.png)

**System information (please complete the following information)**

Joomla version: 4.3.0
Kunena version: 6.0.10
Php version: 7.4
Database version: n/a

**Additional context**

The indicated file /plugins/authentication/joomla/joomla.php was moved to a new directory in Joomla 4.3, namely /plugins/authentication/joomla/src/Extension/Joomla.php .

**Comment by xillibit** [comment] 2023-04-27 15:57
I can't reproduce it, can-you enable please debug mode to see the backtrace ?

**Comment by xillibit** [comment] 2023-09-28 08:12
I close it, re-opened if you are still have with lastest version of Joomla! and Kunena

**Closed as completed by xillibit** 2023-09-28 08:12 UTC
Labels: unconfirmed, no-issue-activity
