### ISSUE TITLE
Unable to subscribe to category

### ISSUE THREAD

**Issue by Ruud68** [Kunena/Kunena-Forum#9041] opened 2022-05-22 08:38 UTC
**Describe the bug**
unable to subscribe to category

**To Reproduce**
1. Go to a category
2. Click on subscribe button

**Expected behavior**
subscribed to category

**Actual result**
error 404 component not found

**Comment by xillibit** [comment] 2022-05-22 14:31
I'am not able to reproduce it

**Comment by Ruud68** [comment] 2022-05-23 06:59
please set in you kunena config the following option:
```
Direct Component Access = No
```
when setting this to yes it works, but when set to no it doesn't

**Comment by rich20** [comment] 2022-06-02 13:48
Confirmed

Call stack
--
# | Function | Location
1 | () | JROOT/components/com_kunena/src/Dispatcher/Dispatcher.php:226
2 | Kunena\Forum\Site\Dispatcher\Dispatcher->checkAccess() | JROOT/components/com_kunena/src/Dispatcher/Dispatcher.php:59
3 | Kunena\Forum\Site\Dispatcher\Dispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:389
4 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/SiteApplication.php:204
5 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT/libraries/src/Application/SiteApplication.php:243
6 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:278
7 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:63
8 | require_once() | JROOT/index.php:32

**Comment by xillibit** [comment] 2023-01-08 21:20
Duplicate fixed by : https://github.com/Kunena/Kunena-Forum/issues/9437

**Closed as completed by xillibit** 2023-01-08 21:20 UTC
Labels: bug, no-issue-activity
