### ISSUE TITLE
Kunena discuss breaks front end

### ISSUE THREAD

**Issue by N6REJ** [Kunena/Kunena-Forum#9699] opened 2024-06-25 15:52 UTC
**Describe the bug**
enabled kunena discuss plugin causes a catastrophic failure to the front end.

**To Reproduce**
1. Go to discus plugin
2. Click on enable
3. go to front end

**Expected behavior**
discus works as designed

**Actual result**
![image](https://github.com/Kunena/Kunena-Forum/assets/1850089/4f906879-c6f3-49cf-8f0b-21a2a03b2a49)

**Screenshots**

**System information (please complete the following information)**

Joomla version:  5.1.1
Kunena version: 6.3.2
Php version: 8.3
Database version: 10.5.24-MariaDB-cll-lve

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] win 11 pro
 - Browser [e.g. chrome, safari] FF & Chrome

**Smartphone (please complete the following information):**

**Additional context**

[systeminfo-2024-06-27T14_10_45+00_00.txt](https://github.com/user-attachments/files/16015372/systeminfo-2024-06-27T14_10_45%2B00_00.txt)

**Comment by N6REJ** [comment] 2024-06-26 23:19
@rich20 I see you gave it an unconfirmed status.  Does this mean you were able to apply discuss without issues to J5?

**Comment by AlisonAMG** [comment] 2024-06-26 23:41
Can confirm this happened. It works flawlessly on the clients J3 site but on J5 we confirmed the settings and turned it on that the issue as shown shuts down the site. Unpublish and the site comes back up.

**Comment by rich20** [comment] 2024-06-27 00:22
> @rich20 I see you gave it an unconfirmed status. Does this mean you were able to apply discuss without issues to J5?

You are right, I cannot reproduce this error. I only add the red bug label if I can reproduce  and confirm an error.

**Comment by N6REJ** [comment] 2024-06-27 05:56
> > @rich20 I see you gave it an unconfirmed status. Does this mean you were able to apply discuss without issues to J5?
> 
> You are right, I cannot reproduce this error. I only add the red bug label if I can reproduce and confirm an error.

Perhaps you can recommend things we can test/check.  From a dev perspective there is nothing a user can do that would trigger this short of screwing with the extension code and that would've been fixed with a re-install of the discuss.  
Keep in mind we are ONLY talking about discuss.

**Comment by rich20** [comment] 2024-06-27 11:05
> Perhaps you can recommend things we can test/check.

Set the error reporting in the Joomla configuration to maximum and enable the debug mode, then you should receive a more accurate error message.

**Comment by N6REJ** [comment] 2024-06-27 14:04
> > Perhaps you can recommend things we can test/check.
> 
> Set the error reporting in the Joomla configuration to maximum and enable the debug mode, then you should receive a more accurate error message.

![image](https://github.com/Kunena/Kunena-Forum/assets/1850089/0ac102e5-067b-4c97-915f-333d1ffb4c26)
fresh download and attempted reinstall using drag-n-drop gives 
![image](https://github.com/Kunena/Kunena-Forum/assets/1850089/c077ec9f-f73f-46de-a7cc-2e88ca04e585)
using file upload with same file gives
![image](https://github.com/Kunena/Kunena-Forum/assets/1850089/f97d6adf-61de-4b1c-8ba5-24436018a085)

so, idk how your not getting the error but its very clearly a kunena discuss issue.

**Comment by Ruud68** [comment] 2024-06-27 16:06
I have just tried this:

1. Joomla 5.1.1
2. install Kunena 6.3.2
3. install Kunena 6.3.2 languages
4. install Kunena discuss 6.0.5

Without issues

Now looking at the error when installing I would like to ask you to add the following code in the Kunena Discuss 6.0.5

File: install.script.php

replace line 17:
```
defined('_JEXEC') or die();
```
with:
```
defined('_JEXEC') or die();

/**
 * We need to 'force' the KunenaDiscussInstallerHelper from the installation package as:
 *  1. autoloading doesn't work on new installs
 *  2. when the KunenaDiscussInstallerHelper is updated we must make sure that it will use the updated version
 */
require_once __DIR__ . '/src/Helper/KunenaDiscussInstallerHelper.php';

```

Can you tell me if that changes anything?

**Comment by N6REJ** [comment] 2024-06-27 16:25
yep, that solved the issue 
[plg_kunenadiscuss_v6.0.5a_2023-12-10.zip](https://github.com/user-attachments/files/16018145/plg_kunenadiscuss_v6.0.5a_2023-12-10.zip)

**Comment by AlisonAMG** [comment] 2024-06-27 16:26
Thank you Ruud and Richard :) Very much appreciated.

**Comment by Ruud68** [comment] 2024-06-28 07:44
just did a PR to the addon repo: https://github.com/Kunena/Kunena-Addons/pull/315

**Comment by xillibit** [comment] 2024-09-10 07:16
The PR has been merged yerstayday

**Closed as completed by xillibit** 2024-09-10 07:16 UTC
Labels: unconfirmed, no-issue-activity, 6.3
