### ISSUE TITLE
Kunena Discuss crashes articles when enabled

### ISSUE THREAD

**Issue by stutteringp0et** [Kunena/Kunena-Forum#5087] opened 2016-12-03 11:56 UTC
#### Steps to reproduce the issue

Kunena 5.0.4 + Kunena Discuss Plugin 5.0.2

When published, 

PHP Notice:  Trying to get property of non-object in /components/com_kunena/template/crypsis/layouts/topic/item/default.php on line 53

PHP Fatal error:  Method KunenaLayout::__toString() must not throw an exception, caught Error: Call to a member function getIcon() on null in /libraries/kunena/view.php on line 0

#### Expected result

article with discussion

#### Actual result

blank page, 2 error logs

#### System information (as much as possible)

Joomla version: 3.6.4
Kunena version: 5.0.4
Php version: 7.0.8
Database version: 5.5.5-10.0.27-MariaDB

#### Additional comments

Just started with 5.0.4, I didn't get any reports with the previous version

**Comment by 810** [comment] 2016-12-03 14:07
Looks like your files isn't updated.

See: https://github.com/Kunena/Kunena-Forum/blob/K5.0/src/components/com_kunena/template/crypsis/layouts/topic/item/default.php#L61

the line is on 61 not on 53

try to uninstall kunena then install kunena again

**Comment by stutteringp0et** [comment] 2016-12-03 20:42
/template/crypsis/layouts/topic/item/default.php line 53 definitely has an object reference:

if ($this->category->headerdesc)

If I add print_r('category:'.gettype($this->category)); two lines above, I'm met with this output:
category:NULL

So, $this->category is a non-object.

Working around it by altering the test to this:

if (is_object($this->category) && property_exists($this->category,'headerdesc') && $this->category->headerdesc)

The only error I receive now is:

PHP Fatal error: Method KunenaLayout::__toString() must not throw an exception, caught Error: Call to a member function getIcon() on null in /libraries/kunena/view.php on line 0

When I change the plugin option from "Show on Articles: Post" to "Show on Articles: Link" - the errors disappear and everything seems to work normally. 

I would prefer to display the discussion on the article, but if this is what I have to do to until it's repaired - so be it.

**Comment by stutteringp0et** [comment] 2016-12-04 00:35
didn't realize I closed it - they need to put a warning

**Comment by 810** [comment] 2016-12-13 23:42
Could you make screenshot from the settings.

I can't reproduce this issue.
Also please update php asap (security updates)

**Comment by CoalaWeb** [comment] 2017-05-26 17:41
I have custom template based on Crypsis and since updating to PHP 7.1 I started getting these errors from some of the layouts:

`PHP Fatal error:  Method KunenaLayout::__toString() must not throw an exception, caught Error: [] operator not supported for strings`

I can't seem to trace why this happening but if you look at the PHP documentation on array assignments, it says this:

> Note: As of PHP 7.1.0, applying the empty index operator on a string throws a fatal error. Formerly, the string was silently converted to an array. 

Put another way, you can look at the "backwards incompatibility" page of the release notes.

> The empty index operator is not supported for strings any-more. Applying the empty index operator to a string (e.g. $str[] = $x) throws a fatal error instead of converting silently to array.

So you have to set arrays to be arrays, not assume they'll be converted silently into arrays when they're needed for that.

Does that help find a solution?

**Comment by qhilen** [comment] 2017-08-17 10:53
I have the same problem: https://klubpodroznikow.com/forum/46-o-wszystkim-innym/14138-nowe-polaczenie-autobusowe-z-warszawy-przez-krakow-do-budapesztu

**Comment by 810** [comment] 2017-08-17 10:57
we have fixed that issue, you can download the nightly build on our download page

**Comment by 810** [comment] 2018-01-19 20:37
@stutteringp0et did you still got this issue, else i will close this issue. Since we can't reproduce this error.

**Closed as completed** 2018-07-26 12:12 UTC
Labels: unconfirmed
