### ISSUE TITLE
Unabled to install sample data from Kunena dashboard

### ISSUE THREAD

**Issue by N6REJ** [Kunena/Kunena-Forum#9704] opened 2024-07-03 12:23 UTC
**Describe the bug**
a card is shown indicating I can install sample data

**To Reproduce**
1. do clean install of Kunena
2. go to dashboard
3. click on "install" on the install sample data card.

**Expected behavior**
sample data is installed

**Actual result**
while it appears as a link, it does nothing

**Screenshots**
![image](https://github.com/Kunena/Kunena-Forum/assets/1850089/50ba009e-362a-4c9b-a306-71f2aa1edaaa)

**System information (please complete the following information)**

Joomla version:  5.1.1
Kunena version:  6.3.2
Php version: 8.1.29
Database version:  10.5.25-MariaDB-cll-lve

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win 11 pro
 - Browser: Chrome
 - Version: 126.0.6478.127 

**Additional context**

**Comment by rich20** [comment] 2024-07-03 23:13
Please ask your questions in the forum. https://www.kunena.org/forum/recent This problem has already been answered several times in the forum and is also described here:  https://docs.kunena.org/en/basics/installation/installation-k6-x
Github is for development and not for support.

**Comment by N6REJ** [comment] 2024-07-03 23:20
I'm sorry @rich20 but I think your reponse is invalid.  This is most definitely a Bug not a support issue.
The "install" button should not be a link if its not going to install.
Yes, using the sample data module in dashboard does the job.  Thats not what I'm reporting per se`

**Comment by rich20** [comment] 2024-07-03 23:35
This bug is already in our bug list: https://github.com/Kunena/Kunena-Forum/issues/8492

**Comment by Pinkeltje** [comment] 2024-07-05 05:58
Unable to reproduce. Install sample data works fine here in Firefox and Chrome.
![2024-07-05 Screenshot 487](https://github.com/Kunena/Kunena-Forum/assets/8941310/e8719649-f7f6-43af-b234-926065e49493)

**Comment by c-schmitz** [comment] 2024-09-06 08:58
Did a fresh install, no problems. I think this can be closed.

**Comment by dengcb** [comment] 2024-11-20 07:55
The bug is still here.
Joomla: 5.2.1
Kunena: 6.3.6

After install, the Sample data and Menus Button do nothing and never disappear.
Actually, menus already created. And I don't need Sample data.

![WX20241120-155226@2x](https://github.com/user-attachments/assets/5fdf7ee4-af76-4a31-be69-e2cc873a6e94)

**Comment by Pinkeltje** [comment] 2024-11-20 08:08
This is not a bug. Could be a server configuration or a PHP version problem or a browser problem. If you continue to experience this issue post your problem on the forum please.
@xillibit I think this issue can be closed.

**Comment by dengcb** [comment] 2024-11-20 08:38
Server: Ubuntu 22.04 with PHP 8.3
Local: MacOS 13.6.7 with Chrome 130 stable and Safari.

And now I find why menus button is still here. Because I edit the menu type...

**Comment by Ruud68** [comment] 2024-12-10 17:05
Hi, just to add to the discussion here:
just did a fresh install of Kunena and I'm unable to install the sample data.
this is the button:
```
<button type="button" class="btn btn-secondary btn-sm apply-sample-data" data-type="kunena" data-steps="1">
                                                    <span class="icon-upload" aria-hidden="true"></span> Install <span class="visually-hidden">Kunena Forum Sample Data</span>
                                                </button>
```
As you can see there is no a element / link on it. So it must be triggered by an event.

But there is also no event assigned to the button.

I think in file: administrator/components/com_kunena/src/vies/Cpanel/HtmlView the script is loaded that enabled the button to actually install the sample data (line 58-50):
```
            Factory::getApplication()->getDocument()->getWebAssetManager()
                ->registerAndUseScript('mod_sampleData', 'mod_sampleData/sampleData-process.js', [], ['defer' => true], ['core']);
```

but and this is IMO why it is not working: sampleData-process.js is never loaded as it doesn't exist?

@Pinkeltje can you check if the sampleData-process.js is loaded on your installation? If so, can you report here what the filepath for this file is?

I searched the complete kunena and kunena-addons repository for this file but it doesn't exists...

**Comment by Pinkeltje** [comment] 2024-12-11 06:58
As far as I can see it uses default Joomla mod_sampleData from /media/mod_sampleData/js/sampleData-process.min.js
Just did fresh install K 6.3.7 again and for me it works without problems. So I suppose a problem with your Joomla installation.

**Comment by Ruud68** [comment] 2024-12-11 08:09
Hi @Pinkeltje thanks for confirming, on my sites there is no mod_sampleData, but there is a mod_sampledata (lowercase d). That is the reason why it doesn't load.
I created a patch for it here #9782

**Closed as completed** 2024-12-11 16:37 UTC
Labels: 6.3
