### ISSUE TITLE
Pages with "404 error" and ending with /unread are being indexed

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5148] opened 2017-01-10 14:07 UTC
#### Steps to reproduce the issue
Take a look into your Google Webmaster Tools (Search Console) and see i you have some errors with the response code 500 caused by URLs ending with /unread 

#### Expected result
Pages with the "500 Error" should not being indexed at all.

#### Actual result
Pages with "404 error" and ending with /unread are being indexed by google and other search engines.

#### System information (as much as possible)

Joomla version: 3.6.5
Kunena version: 5.0.5
Php version: 7.0.14
Database version: MySQL 5.6.34

**Comment by sshcli** [comment] 2017-01-10 14:38
Maybe the http response code are not working as expected
or
aren't enough and needs an additional noindex nofollow

**Comment by 810** [comment] 2017-01-27 15:51
closing this one, can't reproduce this issue

**Closed as completed by 810** 2017-01-27 15:51 UTC

**Comment by sshcli** [comment] 2017-01-27 15:55
ok, no problem

**Comment by sshcli** [comment] 2017-04-21 17:58
Fix: #5325 
https://github.com/Kunena/Kunena-Forum/pull/5325/files
