### ISSUE TITLE
Kunena Forum keeps asking to install Sample Data (backend)

### ISSUE THREAD

**Issue by alecrespi78** [Kunena/Kunena-Forum#9490] opened 2023-03-24 20:36 UTC
**Describe the bug**
Kunena keeps showing the module to install "Sample Data" even if data are present (migrated from previous 5.2 version).

**To Reproduce**
1. Go to backend
2. Click on 'Components', 'Kunena Forum', 'Dashboard'
4. on top of the main page it will show up a module asking to install sample date.

**Expected behavior**
Hiding the module or not showing up because there are already categories / users / files / messages present..

**Actual result**
Asking to install "Sample Data".. 

**Screenshots**
Screenshots.
![kunena6-sample](https://user-images.githubusercontent.com/89710784/227632901-2b493495-cf23-48d3-b288-82a455c459b0.jpg)

**System information (please complete the following information)**

Joomla version: 4.2.9
Kunena version: 6.0.9.1
Php version: 7.4 to 8.2
Database version: 5.7.32-35

**Desktop (please complete the following information):**
 - OS: Win
 - Browser Chrome
 - Version 111.0.5563.111

**Additional context**
Migrated from Kunena 5.2 / Joomla 3.10

**Comment by xillibit** [comment] 2023-03-28 20:23
Similare to this one : https://github.com/Kunena/Kunena-Forum/issues/8459

**Comment by alecrespi78** [comment] 2023-03-29 06:50
In the meantime I've solved this manually setting "sampleData" field to 1 in "#_kunena_version" table.

Here you can find the SQL code I used:
`UPDATE "#_kunena_version" SET "sampleData" = "1" WHERE "#_kunena_version"."id" = 1;`

**Comment by xillibit** [comment] 2024-02-06 15:38
On this one : https://github.com/Kunena/Kunena-Forum/issues/8459 it check on install if there are existing categories and disable the sampledata module. The change will be in the K6.2.4 release, feel free to open issue if the problem is still here.

**Closed as completed by xillibit** 2024-02-06 15:38 UTC
Labels: bug, no-issue-activity
