### ISSUE TITLE
4.0 Beta - Crypsis - Minor Formatting Issues

### ISSUE THREAD

**Issue by GJSchaller** [Kunena/Kunena-Forum#2979] opened 2015-04-15 16:53 UTC
Minor formatting issues in Crypsis for Beta 1

1) The polaroid for the Avatar is not even / level with the "badger" post container.  It's minor, but enough to be annoying to an observer.

2) The "Topic Author" span overflows into the post.

3) Arrows on Drop Menus above & below the post do not line up with their buttons.

These are on Stock Protostar template, with no modifications or custom CSS.

![crypsis-beta-formatting](https://cloud.githubusercontent.com/assets/2761607/7164479/6d8fa76e-e36e-11e4-85fd-5202c549e239.PNG)

**Comment by 810** [comment] 2015-04-25 23:48
1) This is set by design 
2) can't fix this, if you have to small width for your template, there are some issue's.
3) is fixed. 

I'm closing this issue

**Closed by 810** 2015-04-25 23:48 UTC
Labels: 4.0, Crypsis
