### ISSUE TITLE
Set Max Links off by default in Kunena settings

### ISSUE THREAD

**Issue by sozzled** [Kunena/Kunena-Forum#3222] opened 2015-06-14 05:05 UTC
As discussed in #2518, before the topic was arbirarily locked by one team member who did not appreciate the necessity to discuss the issue there.  This is a request that the new Max Links setting be turned off by default.

**Comment by 810** [comment] 2015-06-14 05:27
We will discuss the option in the Team Chat, when we have voted to change, then we will reopen this issue. And do the change. 

If you have more feature wishes, then you should start discussing on the kunena forum. Before opening a new issue.

Any new feature request should be done on the forum, One of our team will create a issue for it, when he has time to start on it. Else we have tons of feature requests but nobody has time to create it. 

For this feature we are closing this issue for now, if we have voted to change then we shall reopen the issue.

**Closed by 810** 2015-06-14 05:27 UTC

**Comment by sozzled** [comment] 2015-06-14 06:04
This is ***not*** a feature request.  It is a report of a bug.

**Comment by 810** [comment] 2015-06-14 06:07
This is not a bug, but a personal opinion.
