### ISSUE TITLE
Only admins and moderators can see private messages

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9482] opened 2023-03-14 18:20 UTC
**System information**
- Joomla version: ‎4.2.9-rc2-dev and ‎4.3.0-beta5-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.1.0-BETA1
- Kunena template: Aurelia
- Php version: 8.1.16
- Database version: 10.5.19-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by rich20** [comment] 2023-03-16 13:51
I have now seen above that there is also a warning message:
**Kunena Internal Error: Please contact the site administrator to fix this issue!**

**Comment by xillibit** [comment] 2023-03-18 21:22
The author of post can see his private message so i'am not able to reproduce this issue

**Comment by rich20** [comment] 2023-03-19 13:46
Apart from the fact that whoever this PM is addressed (if it's a normal user) to cannot see it, the author can only see this if he edits his post. I have this error on both K6.1 installations on Joomla 4.2 and Joomla 4.3
Message: **Kunena Internal Error: Please contact the site administrator to fix this issue!**
This error message has been confirmed
https://www.kunena.org/forum/36-German/167744-k6-1-0-beta-1-fehler-beim-privat-antworten#227661
.
**the author sees that**
.
![Bildschirmfoto vom 2023-03-19 14-14-24](https://user-images.githubusercontent.com/888847/226178647-91e25ee7-5e0a-48ad-9355-73469fd6bbf2.png)
.
**the moderator sees that**
.
![image10236](https://user-images.githubusercontent.com/888847/226179240-d0c0fa68-efc4-4839-9014-df6df348ffad.png)

**Comment by xillibit** [comment] 2023-03-19 14:44
Try with this change : https://github.com/Kunena/Kunena-Forum/commit/4169093d690a8890d1d20e967540076407b7f000 it could be related

**Comment by rich20** [comment] 2023-03-19 18:56
Unfortunately no, it's still the same.

**Comment by xillibit** [comment] 2023-03-19 19:35
The author of message see the private message : 

![image](https://user-images.githubusercontent.com/876395/226204524-4078150a-460a-4d71-966c-3b892f003b73.png)

**Comment by rich20** [comment] 2023-03-19 20:06
Is this message not displayed at the top when you send a message that contains a PM?

**Kunena Internal Error: Please contact the site administrator to fix this issue!**

**Comment by xillibit** [comment] 2023-03-19 20:13
If i write something in both tabs : message and private, i have only `Your message has been successfully posted.` and no error
If i write something only in private tab, i have too `Your message has been successfully posted.` and no error, with that in the normal message : 
![image](https://user-images.githubusercontent.com/876395/226206421-deb8bf1b-9934-415a-ae2a-1f57d789ba5e.png)

**Comment by rich20** [comment] 2023-03-19 21:27
Now I was able to reproduce an error similar to the one this user is experiencing: 
https://www.kunena.org/forum/36-German/167744-k6-1-0-beta-1-fehler-beim-privat-antworten#227654

Maybe this error message will help:

Kunena\Forum\Libraries\Table\KunenaTableMap::add(): Argument #1 ($id) must be of type int, null given, called in .../components/com_kunena/src/Controllers/TopicController.php on line 1122
Call stack
--
# | Function | Location
1 | () | JROOT/libraries/kunena/src/Table/KunenaTableMap.php:255
2 | Kunena\Forum\Libraries\Table\KunenaTableMap->add() | JROOT/components/com_kunena/src/Controllers/TopicController.php:1122
3 | Kunena\Forum\Site\Controllers\TopicController->postPrivate() | JROOT/components/com_kunena/src/Controllers/TopicController.php:863
4 | Kunena\Forum\Site\Controllers\TopicController->post() | JROOT/libraries/kunena/src/Controller/KunenaController.php:319
5 | Kunena\Forum\Libraries\Controller\KunenaController->executeTask() | JROOT/libraries/kunena/src/Controller/KunenaController.php:226
6 | Kunena\Forum\Libraries\Controller\KunenaController->execute() | JROOT/components/com_kunena/src/Dispatcher/Dispatcher.php:108
7 | Kunena\Forum\Site\Dispatcher\Dispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:355
8 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/SiteApplication.php:208
9 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT/libraries/src/Application/SiteApplication.php:249
10 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:294
11 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:61
12 | require_once() | JROOT/index.php:32

</div>

**Comment by xillibit** [comment] 2023-03-22 18:43
Still not able to reproduce, i have no error message

**Comment by rich20** [comment] 2023-03-23 13:30
The problem is that only one user is currently helping us test. So we have no comparison whether the error would also occur with other users.
For me, the error occurs on both test pages, one on Joomla 4.2 and the other Joomla 4.3.
One site was migrated from K5.2 to K6.0 and updated to Kunena 6.1.0-BETA2, the other a fresh install with Kunena 6.0 approx 3 month ago, and updated to Kunena 6.1.0-BETA2.

**Comment by rich20** [comment] 2023-03-25 13:56
Is it correct that the **kunena_private_user_map** table remains empty?

**Comment by xillibit** [comment] 2023-03-26 09:47
It shouldn't be empty

**Comment by rich20** [comment] 2023-03-26 12:51
https://www.kunena.org/forum/36-German/167744-k6-1-0-beta-1-fehler-beim-privat-antworten#227749
Maybe this help.
> Da der übergebene Datensatz php-seitig aber wohl keinen Wert für das Feld definiert hat und das Feld so definiert ist, dass es sich in solchen Fällen keinen Wert selbst "zusammenreimt" (einen Default-Wert), weiß Joomla (besser: Die Datenbank) nicht, was es reinschreiben soll und bricht ab.

I have translated the relevant passage.
An attempt is made to write a record to the table #__kunena_private_user_map. In this table there is a column read_at of type datetime. Since the transferred record on the php page has no value defined for the field, the database does not know what to write into it and aborts.

**Comment by rich20** [comment] 2023-04-07 11:30
The user can see their own PM message now, but the recipient cannot see it.

**Comment by rich20** [comment] 2023-04-07 17:09
I have found the cause. During an upgrade, the database table kunena_private_user_map is not updated. After I adjusted this table manually, reading a PM also works.

**Comment by xillibit** [comment] 2023-04-11 21:00
So with https://github.com/Kunena/Kunena-Forum/commit/fdd533e15e457b3ebae59897aa2738bf5363a6ad i can close it

**Closed as completed by xillibit** 2023-04-11 21:00 UTC
Labels: bug
